### ISSUE TITLE
Method remove_foreign_key() does not work in MySQL

### ISSUE THREAD

**Issue by qertoip** [mlomnicki/redhillonrails_core#5]
MySQL does not accept "...DROP CONSTRAINT..." statement for dropping foreign keys. Please use "...DROP FOREIGN KEY...".

**Comment by mlomnicki** [comment]
we use ALTER TABLE ... DROP FOREIGN KEY ... syntax already.
https://github.com/mlomnicki/redhillonrails_core/blob/master/lib/red_hill_consulting/core/active_record/connection_adapters/mysql_adapter.rb#L29

Could you provide more details about your issue?

regards,
Michał

**Comment by qertoip** [comment]
For some reason the method from AbstractAdapter is used. I use Rails 3.0.3 with mysql2 adapter set in database.yml.

**Comment by mlomnicki** [comment]
Thanks for reporting that issue. As you've mentioned the problem was caused by mysql2 gem. redhillonrails_core 1.0.9 fixes that issue.
