### ISSUE TITLE
#change_column doesn't respect :references

### ISSUE THREAD

**Issue by francois** [mlomnicki/redhillonrails_core#6]
When I do:

```
change_column :segments, :parent_id, :integer, :references => :segments, :null => false
```

The foreign key constraint isn't added.

**Comment by mlomnicki** [comment]
That's not redhillonrails_core issue. It does support add_foreign_key / remove_foreign_key methods only. We don't plug into add_column / change_column here.

I've moved to https://github.com/mlomnicki/automatic_foreign_key/issues/issue/2

**Comment by francois** [comment]
Oops, so very sorry! That'll teach me to report and not check...
