### ISSUE TITLE
Foreign key dumping and "drop table" fails for mysql with activerecord-jdbc-adapter

### ISSUE THREAD

**Issue by donv** [mlomnicki/redhillonrails_core#7]
The redhillonrails_core methods for mysql use index based columns when listing foreign keys, and these are not supported by activerecord-jdbc-adapter.

I have a fix that simply uses the names of the columns instead of the column indexes in the result set.

**Comment by mlomnicki** [comment]
Hi donv!

Thanks for reporting the issue. Could you give me some more details?
- config/database.yml
- gem list
- code of your fix is also very welcome

cheers!

**Comment by donv** [comment]
Switched to schema_plus, so this issue is not relevant anymore.
